version: "3"

networks:
  pavit-network:

# volumes:
#   app_data: {}

  # docker run -it --rm  --name flask-api -v $(pwd):/api -w /api -p 5000:5000  \
  # --env PROMETHEUS_MULTIPROC_DIR=prometheus_multiproc --network flask-prometheus-grafana-example_pavit-network wave_flask
services:
  flask-api:
    build:
      context: ./api
    restart: unless-stopped
    container_name: flask-api
    image: wave_flask
    environment:
      - PROMETHEUS_MULTIPROC_DIR=prometheus_multiproc
    volumes:
      - ./api:/api
    working_dir: /api
    ports:
      - 5000:5000
    networks:
      - pavit-network

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - pavit-network

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - pavit-network
